//
// Created by 张开顺 on 2018/11/27.
//

#ifndef CLOSPAN_STUDY_SEQTREE_H
#define CLOSPAN_STUDY_SEQTREE_H

#define _FIND_FREQUENT_SEQS
#define _CALC_I_NUM_OF_ITEMS
#define _ANOTHER_CLOSED_APPROACH


#endif //CLOSPAN_STUDY_SEQTREE_H
